apiVersion: apps/v1
kind: Deployment
metadata:
  name: toshkalab27
  labels:
    app: webnginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginxwebpod
  template:
    metadata:
      labels:
        app: nginxwebpod
    spec:
      containers:
      - name: nginx
        image: toshkawai/lab27:1.0.0
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: toshkalab27
spec:
  selector:
    app: nginxwebpod
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

